packages:
  - apps/*
  - packages/*

allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: true
  ssh2: false

minimumReleaseAgeExclude:
  - "@aws-sdk/client-s3@3.1127.0"
  - "@aws-sdk/s3-request-presigner@3.1127.0"
